### ISSUE TITLE
How to create Two CentOS?

### ISSUE THREAD

**Issue by JarboU** [mishamosher/CentOS-WSL#12]

**Comment by mishamosher** [comment]
You can use different names for each WSL instance.

One way to accomplish this is to rename the .exe to anything you want, as it used as the unique identifier of the WSL instance.

Another way is to import the `rootfs.tar.gz` file manually via the `wsl.exe` tool, specifying a unique identifier for each WSL instance: [Import the tar file into WSL](https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro#import-the-tar-file-into-wsl)

**Comment by JarboU** [comment]
Great！Thanks~
