### ISSUE TITLE
Hi, question is there will be a CentOS WSL 2 Version

### ISSUE THREAD

**Issue by ayami123** [mishamosher/CentOS-WSL#13]
Just a Question ?

**Comment by mishamosher** [comment]
Hello!

This is not something that depends on the RootFS, but on the host Windows OS itself. Please refer to the official docs for a how-to management of the WSL version:

- [Check which version of WSL you are running](https://docs.microsoft.com/en-us/windows/wsl/install#check-which-version-of-wsl-you-are-running)
- [Upgrade version from WSL 1 to WSL 2](https://docs.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2)
