### ISSUE TITLE
Launches into root account - would like to launch into un-elevated user profile

### ISSUE THREAD

**Issue by tbraun84** [mishamosher/CentOS-WSL#16]
To prevent me from doing something foolish, I would like to launch CentOS with a non-root account. Is this setting "visible" in the builds?

**Comment by Vinfall** [comment]
It's built using [wsldl](https://github.com/yuk7/wsldl) (see https://github.com/mishamosher/CentOS-WSL/blob/9-stream/build.sh#L16) . You can run `.\CentOS.exe config --default-user averagejoe` to set the default user as `averagejoe`.

Or more universally, you can run the distro with `--user handsomejake` param setting in Windows Terminal or [set User in `/etc/wsl.conf`](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#user-settings) inside WSL:

```sh
# Set the user when launching a distribution with WSL.
[user]
default = DemoUser
```
