### ISSUE TITLE
How to manage services？such as systemctl

### ISSUE THREAD

**Issue by dong-lufei** [mishamosher/CentOS-WSL#18]
Your CentOS9 does not seem to recognize systemctl and service

By the way, do you want something else like Ubuntu-WSL

**Comment by dong-lufei** [comment]
How to enable or manage this version of process service?

I get an error as soon as I use the command

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by felixserna** [comment]
Create a file "/etc/wsl.conf" with content like this:

[boot]
systemd=true


And reboot  wsl.

**Comment by FlowerBirds** [comment]
> Create a file "/etc/wsl.conf" with content like this:
> 
> [boot] systemd=true
> 
> And reboot wsl.

It dost not work！

**Comment by FlowerBirds** [comment]
```bash
mv /usr/bin/systemctl /usr/bin/systemctl.old
curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py > /usr/bin/systemctl
chmod +x /usr/bin/systemctl
```

**Comment by FlowerBirds** [comment]
The problem is solved：

```
PS C:\Users\merit> wsl -l -v
  NAME                   STATE           VERSION
* alpine                 Stopped         2
  Rocky9                 Stopped         2
  docker-desktop-data    Stopped         2
  kali-linux             Stopped         2
  docker-desktop         Stopped         2
  ubuntu1804             Stopped         2
  CentOS7                Stopped         2
PS C:\Users\merit> wsl --version
WSL 版本： 1.1.3.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.49
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22000.1574
```
update wsl2 ifself, then the file "/etc/wsl.conf" will take effect.

**Comment by mishamosher** [comment]
For an alternative under WSL1, please see https://github.com/mishamosher/CentOS-WSL/issues/7
