### ISSUE TITLE
F&Q

### ISSUE THREAD

**Issue by MilesYyh** [mishamosher/CentOS-WSL#19]
Hi,sir!
I would like to ask a question, I used to install centos6.exe, but when I open centos6 in cmd, it can not enter the system, there will be a report error, 
(Processing fstab with mount -a failed.)

I installed centos7, 8 are no problem, because some need I need to install centos6

**Comment by haozi5219** [comment]
你可以使用以下命令直接进入 centos6 操作系统，我也没有更好的办法，但是这样确实是可以使用的

wsl.exe --user root

**Comment by mishamosher** [comment]
Hello!

Sorry for the long time.

- Are you using WSL2?
- Have you configured `vsyscall=emulate`?

**Comment by MilesYyh** [comment]
Never mind!! Thank!! 
I have already figured out this problem by setting configuration of the Window system.

**Comment by mishamosher** [comment]
Glad you got it sorted out (:
