### ISSUE TITLE
Build scripts and CI/CD configuration

### ISSUE THREAD

**Issue by knu73r1k** [mishamosher/CentOS-WSL#2]
Hi - thanks @mishamosher  for sharing your prebuild wsl images.

Is it possible for you to share how your ci/cd is for converting the QCOW2 files, to wsl images? Any writeup or repo which could be read?

Thanks.

**Comment by mishamosher** [comment]
Hi there!

Please inspect the repo more thoroughly (:

Branches: https://github.com/mishamosher/CentOS-WSL/branches

Each branch has a build script and the Travis YML.

In fact, all the WSL images in this repo are not prebuilt. You can check the corresponding Travis for logs and details: https://travis-ci.com/github/mishamosher/CentOS-WSL/builds/

There is not much to write/describe. It is a simple matter of creating a free Travis account, copy the `build.sh` and `.travis.yml` files to a new GitHub repo, and follow the abundant documentation about the Travis CI integration with GitHub.

**Comment by knu73r1k** [comment]
Ahh sorry about that (not inspecting the repo enough), thanks for feedback and explanation!
