### ISSUE TITLE
Kernel does not support multicast on CentOS7

### ISSUE THREAD

**Issue by 772435284** [mishamosher/CentOS-WSL#21]
When I run `netstat -g`, it shows "netstat: no support for `AF INET (igmp)' on this system", which means igmp/multicast is not compiled in this kernel, can you recompiled a new kernel for wsl CentOS7?

**Comment by mishamosher** [comment]
This image does not contain any kernel, and adding a custom-mantained one is out of the scope of this repo (and my available time, unfortunately).

On WSL1 a compatibility layer similar to WINE is provided by Windows.

On WSL2 a default kernel is provided by: https://github.com/microsoft/WSL2-Linux-Kernel

There are plenty of alternative WSL2 kernels on the Internet. Examples: https://github.com/topics/wsl2-kernel
