### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by hwc0919** [mishamosher/CentOS-WSL#5]
After first successful installation, I can enter the terminal using CentOS.exe.

Then I want to see if I can move the folder, so I move it from desktop (C:\Users\nitromelon\Desktop\CentOS8) to another place ( X:\CentOS8).
After moving,  running CentOS8.exe will get stuck forever. I tried deleting all files, rebooting my system, and unzip CentOS8.zip again, but it still gets stuck when running CentOS8.exe

What should I do now?

**Comment by mishamosher** [comment]
Have you tried using `wsl.exe` to manage your WSL distros?

https://docs.microsoft.com/en-us/windows/wsl/wsl-config#unregister-and-reinstall-a-distribution

**Comment by hwc0919** [comment]
Thank you so much. It's all good now with the help of wsl.exe.
